# Generated by Django 3.1 on 2020-10-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic: False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='intro.book')),
            ],
        ),
    ]
