# Generated by Django 3.1 on 2020-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic: False
    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
