# Generated by Django 3.1 on 2020-10-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic: False
    dependencies = [
        ('intro', '0002_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookDescription',
        ),
    ]
