# Generated by Django 3.1 on 2020-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0003_auto_20201018_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField(null=True)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
