# Generated by Django 3.1 on 2020-10-22 03:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articletext',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
