# Generated by Django 3.1 on 2020-10-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0005_article_articletext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
