# Generated by Django 3.1 on 2020-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False 
    dependencies = [
        ('intro', '0006_auto_20201022_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverBooks',
            fields=[
                ('discoverid', models.IntegerField(primary_key=True, serialize=False)),
                ('discovertitle', models.CharField(max_length=200)),
                ('discoverauthor', models.CharField(max_length=200)),
                ('discoverdescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=200)),
            ],
        ),
    ]
