# Generated by Django 3.1 on 2020-10-31 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0007_discoverbooks_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rateid', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('discoverbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.discoverbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.user')),
            ],
        ),
    ]
