# Generated by Django 3.1 on 2020-11-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoverbooks',
            old_name='discoverid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rateid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='discoverbooks',
            name='discovervolumeid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
