# Generated by Django 3.1 on 2020-11-02 03:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0009_auto_20201102_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='discoverbook',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscoverBooks',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
