# Generated by Django 3.1 on 2020-11-02 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('intro', '0010_auto_20201102_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discovertitle', models.CharField(max_length=200)),
                ('discoverauthor', models.CharField(max_length=200)),
                ('discoverdescription', models.TextField(blank=True, null=True)),
                ('discovervolumeid', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('discoverbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.discoverbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', tinymce.models.HTMLField()),
                ('date', models.DateField(blank=True, null=True)),
                ('discoverbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.discoverbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.user')),
            ],
        ),
    ]
