# Generated by Django 3.1 on 2020-11-09 17:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('intro', '0012_auto_20201109_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookid',
            new_name='id',
        ),
    ]
