# Generated by Django 3.1 on 2020-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('intro', '0013_auto_20201109_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='bookid',
        ),
        migrations.AlterField(
            model_name='recommendationlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
