# Generated by Django 3.1 on 2020-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('intro', '0014_auto_20201109_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='pinned',
            field=models.IntegerField(default=0),
        ),
    ]
