# Generated by Django 3.1 on 2020-11-10 11:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('intro', '0015_auto_20201110_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pinned',
        ),
    ]
