# Generated by Django 3.1 on 2020-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0016_remove_article_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
